name: sync-to-bitbucket
on: [push]
jobs:
  mirror_to_bitbucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # <-- clone with complete history
      - name: Push
        uses: heussd/mirror-to-bitbucket-github-action@v2
        with:
          password: ${{ secrets.BITBUCKET_PASSWORD }}
